#1
list=['rwer','rewrfrg','gzxda','gvsgt']
c='kapets'
list.append(c)
print(list)
#2
list1=['rwer','rewrfrg','gzxda','gvsgt']
c='kapets'
list1.insert(1,c)
print(list1)
#3
drop=['ddd','fff','yyy']
drop2=['rrr','tttt','pepepe']
drop.extend(drop2)
print(drop)
#4
drop3=['ddd','fff','yyy']
drop4=('rrr','tttt','pepepe')
drop3.extend(drop4)
print(drop3)